services:
  camera-agent:
    build: .
    container_name: camera-agent
    restart: unless-stopped
    networks:
      prosody_xmpp_network:
        ipv4_address: 172.20.0.6
    ports:
      - 3001:3001
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_USERNAME: camera_agent
      XMPP_PASSWORD: top_secret
      HTTP_PORT: 3001
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
    devices:
      - /dev/video0:/dev/video0
    privileged: true

networks:
  prosody_xmpp_network:
    external: true
