services:
  camera-agent:
    build: .
    container_name: camera-agent
    restart: unless-stopped
    networks:
      - prosody_xmpp_network
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_USERNAME: camera_agent
      XMPP_PASSWORD: top_secret
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
    devices:
      - /dev/video2:/dev/video0
    privileged: true

networks:
  prosody_xmpp_network:
    external: true
